### ISSUE TITLE
Problem: zpipes retains data for disconnected pipes

### ISSUE THREAD

**Issue by rpedde** [zeromq/zbroker#23] opened 2014-03-25 22:57 UTC
Named pipe semantics are to flush the pipe contents when both reader and writer disconnect.  I think that's probably the expected behavior here.  It's very surprising to connect to an "old" pipe and find data in it.

**Comment by hintjens** [comment] 2014-03-25 23:01
Ah, indeed. The problem is if a writer opens, stores, closes, and then a
reader comes along, the pipe has been deleted.

How do we define "disconnect"? Shall we do heartbeating in the protocol and
assume a dead reader/writer after a certain timeout?

**Comment by rpedde** [comment] 2014-03-27 02:19
A writer should block until a reader connects, so this is okay.  What I'm observing is: write a chunk to the server, blocks until reader connects.  Write another block, close the writer.  Read one block by the reader, close the reader.  The last block sits on the server indefinitely until that pipe accidentally gets opened again and surprise!  existing data is there.  :)

Synchronous writes would take care of this as well.

As far as dirty disconnects, I think one has to be able to detect ungracefully terminated connections, else the server slowly eats memory.  And I guess that pretty much has to be heartbeating.

**Comment by hintjens** [comment] 2014-03-27 07:23
Closing this, replacing with #25 and #26.

**Comment by hintjens** [comment] 2014-03-29 19:03
Reopening this, it's a separate issue.

**Closed as completed** 2014-03-30 12:50 UTC
Labels: Ready
